#!/usr/bin/env node
/**
 * Build script: Generate examples/keys.js from environment variables.
 *
 * Priority:
 * 1. Netlify/build env vars (MAPBOX_PUBLIC_TOKEN, GOOGLE_MAPS_API_KEY, etc.)
 * 2. Local .env file (if present)
 * 3. Empty string - app will show missing-key notification
 *
 * Netlify env var names -> keys.js var names:
 *   MAPBOX_PUBLIC_TOKEN  -> MAPBOX_KEY
 *   GOOGLE_MAPS_API_KEY  -> GOOGLE_KEY
 *   CESIUM_ION_ACCESS_TOKEN -> CESIUM_ION_TOKEN
 *   NEARMAP_API_KEY      -> NEARMAP_KEY
 */

const fs = require('fs');
const path = require('path');

// Try to load .env for local fallback
try {
  const dotenv = require('dotenv');
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
  }
} catch (e) {
  // dotenv not installed - skip
}

function get(key, envNames = []) {
  for (const n of envNames) {
    const v = process.env[n];
    if (v && typeof v === 'string' && v.trim()) return v.trim();
  }
  return '';
}

const keys = {
  NEARMAP_KEY: get('NEARMAP_KEY', ['NEARMAP_API_KEY', 'NEARMAP_KEY']),
  MAPBOX_KEY: get('MAPBOX_KEY', ['MAPBOX_PUBLIC_TOKEN', 'MAPBOX_KEY']),
  GOOGLE_KEY: get('GOOGLE_KEY', ['GOOGLE_MAPS_API_KEY', 'GOOGLE_KEY']),
  CESIUM_ION_TOKEN: get('CESIUM_ION_TOKEN', ['CESIUM_ION_ACCESS_TOKEN', 'CESIUM_ION_TOKEN'])
};

const outPath = path.join(__dirname, '..', 'examples', 'keys.js');
const content = `/**
 * API Keys - Auto-generated by scripts/build-keys.js
 * Sources: Netlify env vars, then .env, then empty (shows error if missing)
 * Never commit real keys - this file is gitignored.
 */
var NEARMAP_KEY = ${JSON.stringify(keys.NEARMAP_KEY)};
var MAPBOX_KEY = ${JSON.stringify(keys.MAPBOX_KEY)};
var GOOGLE_KEY = ${JSON.stringify(keys.GOOGLE_KEY)};
var CESIUM_ION_TOKEN = ${JSON.stringify(keys.CESIUM_ION_TOKEN)};

(function() {
  var KEY_DEFINITIONS = {
    NEARMAP_KEY: { label: 'Nearmap API Key', url: 'https://docs.nearmap.com/display/ND/Work+with+API+Keys' },
    MAPBOX_KEY: { label: 'Mapbox Token', url: 'https://account.mapbox.com' },
    GOOGLE_KEY: { label: 'Google Maps API Key', url: 'https://console.cloud.google.com' },
    CESIUM_ION_TOKEN: { label: 'Cesium Ion Token', url: 'https://cesium.com/ion/' }
  };
  var PLACEHOLDER_PATTERN = /YOUR_|\\.\\.\\./;
  function isKeyMissing(keyName) {
    var value = typeof window[keyName] !== 'undefined' ? window[keyName] : '';
    var s = String(value || '').trim();
    return !s || PLACEHOLDER_PATTERN.test(s);
  }
  function getMissingKeys() {
    var missing = [];
    for (var key in KEY_DEFINITIONS) {
      if (isKeyMissing(key)) missing.push({ name: key, info: KEY_DEFINITIONS[key] });
    }
    return missing;
  }
  function showNotification(missing) {
    if (missing.length === 0) return;
    var banner = document.createElement('div');
    banner.id = 'nearmap-api-key-notification';
    banner.setAttribute('role', 'alert');
    banner.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:99999;padding:12px 16px;background:#d32f2f;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:14px;line-height:1.5;box-shadow:0 2px 8px rgba(0,0,0,0.2);display:flex;align-items:flex-start;gap:12px';
    var keyList = missing.map(function(k) { return k.info.label + ' (' + k.name + ')'; }).join(', ');
    var msg = document.createElement('div');
    msg.style.flex = '1';
    msg.innerHTML = '<strong>Missing API keys:</strong> This example cannot load without API keys. Add keys via Netlify env vars (<code>MAPBOX_PUBLIC_TOKEN</code>, <code>GOOGLE_MAPS_API_KEY</code>, <code>CESIUM_ION_ACCESS_TOKEN</code>) or local <code>.env</code> / <code>examples/keys.js</code>. Missing: ' + keyList + '.';
    var btn = document.createElement('button');
    btn.textContent = 'Dismiss';
    btn.style.cssText = 'background:rgba(255,255,255,0.2);border:1px solid rgba(255,255,255,0.5);color:#fff;padding:6px 12px;cursor:pointer;font-size:13px;border-radius:4px;flex-shrink:0';
    btn.onclick = function() { banner.remove(); };
    banner.appendChild(msg);
    banner.appendChild(btn);
    function append() {
      if (document.body) document.body.insertBefore(banner, document.body.firstChild);
      else document.addEventListener('DOMContentLoaded', append);
    }
    append();
  }
  var missing = getMissingKeys();
  if (missing.length > 0) showNotification(missing);
})();
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated examples/keys.js from env vars');
