#!/usr/bin/env node
/**
 * Build script: Generate examples/keys.js from environment variables.
 *
 * Priority:
 * 1. Netlify/build env vars (MAPBOX_PUBLIC_TOKEN, GOOGLE_MAPS_API_KEY, etc.)
 * 2. Local .env file (if present)
 * 3. Empty string - app will show missing-key notification
 *
 * Netlify env var names -> keys.js var names:
 *   MAPBOX_PUBLIC_TOKEN  -> MAPBOX_KEY
 *   GOOGLE_MAPS_API_KEY  -> GOOGLE_KEY
 *   CESIUM_ION_ACCESS_TOKEN -> CESIUM_ION_TOKEN
 *   NEARMAP_API_KEY      -> NEARMAP_KEY
 *   LAUNCHDARKLY_CLIENT_ID -> LAUNCHDARKLY_CLIENT_ID
 */

const fs = require('fs');
const path = require('path');

// Try to load .env for local fallback
try {
  const dotenv = require('dotenv');
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
  }
} catch (e) {
  // dotenv not installed - skip
}

function get(key, envNames = []) {
  for (const n of envNames) {
    const v = process.env[n];
    if (v && typeof v === 'string' && v.trim()) return v.trim();
  }
  return '';
}

const keys = {
  NEARMAP_KEY: get('NEARMAP_KEY', ['NEARMAP_API_KEY', 'NEARMAP_KEY']),
  MAPBOX_KEY: get('MAPBOX_KEY', ['MAPBOX_PUBLIC_TOKEN', 'MAPBOX_KEY']),
  GOOGLE_KEY: get('GOOGLE_KEY', ['GOOGLE_MAPS_API_KEY', 'GOOGLE_KEY']),
  CESIUM_ION_TOKEN: get('CESIUM_ION_TOKEN', ['CESIUM_ION_ACCESS_TOKEN', 'CESIUM_ION_TOKEN']),
  LAUNCHDARKLY_CLIENT_ID: get('LAUNCHDARKLY_CLIENT_ID', ['LAUNCHDARKLY_CLIENT_ID'])
};

const outPath = path.join(__dirname, '..', 'examples', 'keys.js');
const content = `/**
 * API Keys - Auto-generated by scripts/build-keys.js
 * Sources: Netlify env vars, then .env, then empty (shows error if missing)
 * Never commit real keys - this file is gitignored.
 */
var NEARMAP_KEY = ${JSON.stringify(keys.NEARMAP_KEY)};
var MAPBOX_KEY = ${JSON.stringify(keys.MAPBOX_KEY)};
var GOOGLE_KEY = ${JSON.stringify(keys.GOOGLE_KEY)};
var CESIUM_ION_TOKEN = ${JSON.stringify(keys.CESIUM_ION_TOKEN)};
var LAUNCHDARKLY_CLIENT_ID = ${JSON.stringify(keys.LAUNCHDARKLY_CLIENT_ID)};

(function() {
  var KEY_DEFINITIONS = {
    NEARMAP_KEY: { label: 'Nearmap API Key', url: 'https://docs.nearmap.com/display/ND/Work+with+API+Keys' },
    MAPBOX_KEY: { label: 'Mapbox Token', url: 'https://account.mapbox.com' },
    GOOGLE_KEY: { label: 'Google Maps API Key', url: 'https://console.cloud.google.com' },
    CESIUM_ION_TOKEN: { label: 'Cesium Ion Token', url: 'https://cesium.com/ion/' }
  };
  var PLACEHOLDER_PATTERN = /YOUR_|\\.\\.\\./;
  function isKeyMissing(keyName) {
    var value = typeof window[keyName] !== 'undefined' ? window[keyName] : '';
    var s = String(value || '').trim();
    return !s || PLACEHOLDER_PATTERN.test(s);
  }
  function getMissingKeys() {
    var missing = [];
    for (var key in KEY_DEFINITIONS) {
      if (isKeyMissing(key)) missing.push({ name: key, info: KEY_DEFINITIONS[key] });
    }
    return missing;
  }
  function showNotification(missing) {
    if (missing.length === 0) return;
    var banner = document.createElement('div');
    banner.id = 'nearmap-api-key-notification';
    banner.setAttribute('role', 'alert');
    banner.style.cssText = 'position:fixed;bottom:12px;right:12px;z-index:99999;padding:10px 14px;background:rgba(50,50,50,0.9);color:rgba(255,255,255,0.85);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:12px;line-height:1.4;border-radius:8px;box-shadow:0 2px 12px rgba(0,0,0,0.15);display:flex;align-items:center;gap:10px;max-width:360px;backdrop-filter:blur(8px)';
    var keyList = missing.map(function(k) { return k.info.label; }).join(', ');
    var msg = document.createElement('div');
    msg.style.flex = '1';
    msg.innerHTML = '<strong style="color:#ffb74d">Missing keys:</strong> ' + keyList;
    var btn = document.createElement('button');
    btn.textContent = '\u00d7';
    btn.style.cssText = 'background:none;border:none;color:rgba(255,255,255,0.5);padding:0 2px;cursor:pointer;font-size:18px;line-height:1;flex-shrink:0';
    btn.onmouseover = function() { btn.style.color = '#fff'; };
    btn.onmouseout = function() { btn.style.color = 'rgba(255,255,255,0.5)'; };
    btn.onclick = function() { banner.remove(); };
    banner.appendChild(msg);
    banner.appendChild(btn);
    function append() {
      if (document.body) document.body.appendChild(banner);
      else document.addEventListener('DOMContentLoaded', append);
    }
    append();
  }
  var missing = getMissingKeys();
  if (missing.length > 0) showNotification(missing);
})();
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated examples/keys.js from env vars');
